//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore2.Web.WebStore2Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebStore2Service.IWebStoreService")]
    public interface IWebStoreService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebStoreService/GetProducts", ReplyAction="http://tempuri.org/IWebStoreService/GetProductsResponse")]
        WebStore2.Domain.OrdersService.ProductDataContract[] GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebStoreService/GetProducts", ReplyAction="http://tempuri.org/IWebStoreService/GetProductsResponse")]
        System.Threading.Tasks.Task<WebStore2.Domain.OrdersService.ProductDataContract[]> GetProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebStoreService/RemoveAt", ReplyAction="http://tempuri.org/IWebStoreService/RemoveAtResponse")]
        bool RemoveAt(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebStoreService/RemoveAt", ReplyAction="http://tempuri.org/IWebStoreService/RemoveAtResponse")]
        System.Threading.Tasks.Task<bool> RemoveAtAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebStoreService/GetData", ReplyAction="http://tempuri.org/IWebStoreService/GetDataResponse")]
        string GetData(int val);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebStoreService/GetData", ReplyAction="http://tempuri.org/IWebStoreService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int val);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebStoreServiceChannel : WebStore2.Web.WebStore2Service.IWebStoreService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebStoreServiceClient : System.ServiceModel.ClientBase<WebStore2.Web.WebStore2Service.IWebStoreService>, WebStore2.Web.WebStore2Service.IWebStoreService {
        
        public WebStoreServiceClient() {
        }
        
        public WebStoreServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebStoreServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebStoreServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebStoreServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebStore2.Domain.OrdersService.ProductDataContract[] GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public System.Threading.Tasks.Task<WebStore2.Domain.OrdersService.ProductDataContract[]> GetProductsAsync() {
            return base.Channel.GetProductsAsync();
        }
        
        public bool RemoveAt(int id) {
            return base.Channel.RemoveAt(id);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveAtAsync(int id) {
            return base.Channel.RemoveAtAsync(id);
        }
        
        public string GetData(int val) {
            return base.Channel.GetData(val);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int val) {
            return base.Channel.GetDataAsync(val);
        }
    }
}
