//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore2.Web.WebStore2Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebStore2Service.IWebStoreService")]
    public interface IWebStoreService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebStoreService/GetProducts", ReplyAction="http://tempuri.org/IWebStoreService/GetProductsResponse")]
        WebStore2.Domain.OrdersService.ProductDataContract[] GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebStoreService/GetProducts", ReplyAction="http://tempuri.org/IWebStoreService/GetProductsResponse")]
        System.Threading.Tasks.Task<WebStore2.Domain.OrdersService.ProductDataContract[]> GetProductsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebStoreServiceChannel : WebStore2.Web.WebStore2Service.IWebStoreService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebStoreServiceClient : System.ServiceModel.ClientBase<WebStore2.Web.WebStore2Service.IWebStoreService>, WebStore2.Web.WebStore2Service.IWebStoreService {
        
        public WebStoreServiceClient() {
        }
        
        public WebStoreServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebStoreServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebStoreServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebStoreServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebStore2.Domain.OrdersService.ProductDataContract[] GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public System.Threading.Tasks.Task<WebStore2.Domain.OrdersService.ProductDataContract[]> GetProductsAsync() {
            return base.Channel.GetProductsAsync();
        }
    }
}
